{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-manager.serviceAccountTokenSecretName" . }}
  labels:
    {{- include "argocd-manager.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "argocd-manager.serviceAccountName" . }}
  {{- with .Values.serviceAccount.tokenSecret.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
