{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd-manager.serviceAccountName" . }}
  labels:
    {{- include "argocd-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ include "argocd-manager.serviceAccountTokenSecretName" . }}
{{- end }}
