# Default values for mongosh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deploy as DaemonSet or Deployment
kind: Deployment

# Specify replica count in case of Deployment
replicaCount: 1

image:
  repository: rtsp/mongosh
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 1m
    memory: 1Mi

nodeSelector: {}

tolerations: []

affinity: {}
